version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: huemul-db 
    restart: unless-stopped
    ports: 
      - 5434:5432
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: